# O comando para construir o aplicativo
buildCommand = "pip install -r requirements.txt --target /workspace"

# O comando para iniciar o aplicativo
runCommand = "python index.py"

# Arquivos a serem ignorados durante o deploy
ignore = [
  ".gitignore",
  "README.md"
]
