[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt --target /workspace"

[deploy]
startCommand = "python index.py"
healthcheckPath = "/get_all_drinks"
healthcheckTimeout = 100
restartPolicyType = "Never"
