[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt --target /workspace"

[deploy]
startCommand = "gunicorn index:app"
healthcheckPath = "/get-all-drinks"
healthcheckTimeout = 100
restartPolicyType = "Never"
