[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt --target /workspace"

[deploy]
startCommand = "gunicorn -b 0.0.0.0:8000 index:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "Never"
